### ISSUE TITLE
missing snippet check

### ISSUE THREAD

**Issue by tskorupa** [Shopify/theme-check#102]
```
def test_report_on_missing_snippet
  offenses = analyze_theme(
    "templates/index.liquid" => <<~END,
      {% render 'collection' %}
    END
  )
  assert_offenses(<<~END, offenses)
    Missing snippet `collection` at templates/index.liquid:1
  END
end
```

**Comment by macournoyer** [comment]
I think `MissingTemplate` already covers this: 
https://github.com/Shopify/theme-check/blob/master/test/checks/missing_template_test.rb

I realize now that name `Template` might be confusing... perhaps it should be renamed to MissingSnippet? But it also covers section templates...

**Comment by tskorupa** [comment]
I missed it :-/. Thank you for pointing it out :-D.
