### ISSUE TITLE
VScode extension missing from wiki

### ISSUE THREAD

**Issue by Agonn** [Shopify/theme-check#109]
https://github.com/Shopify/theme-check-vscode/releases returns a 404

**Comment by macournoyer** [comment]
We're finalizing the installation process of the extension before open sourcing it. Should be available soon 🎉

**Comment by charlespwd** [comment]
It's open source!

You can find it on the [VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=Shopify.theme-check-vscode).

I also updated the docs to reflect this change.
