### ISSUE TITLE
Don't report Shopify-defined translation keys as missing

### ISSUE THREAD

**Issue by cshold** [Shopify/theme-check#114]
This tool is *amazing*.

Small thing - this error is an edge case and shouldn't come up because the string is defined by Shopify, not the theme. Shopify detects if it exists before deciding on showing the Google Captcha button on the lower right of the screen 

![image](https://user-images.githubusercontent.com/1730309/105208492-be986a80-5b16-11eb-9c74-73c3d3dc835d.png)

**Comment by charlespwd** [comment]
Hiya! A PR is open to fix this. There's one asterisk though:

Only the translations that a merchant can edit in the Language Editor are surfaced. The one shown in the screenshot you posted is technically undocumented. I'm making inquiries internally to figure out if this is a bug or intentional.
