### ISSUE TITLE
[Bug] Undefined object error when rendering snippet with optional parameters

### ISSUE THREAD

**Issue by tyleralsbury** [Shopify/theme-check#133]
## Problem

Sometimes in themes, we will render a snippet using "optional" parameters.

### Example:

``` liquid
 {% render 'product-card', media_size: section.settings.product_image_ratio %}
```

**The corresponding snippet can accept up to 5 parameters:**

``` liquid
{% comment %}
    Renders a product card

    Accepts:
    - product_card_product: {Object} Product Liquid object (optional)
    - show_vendor: {Boolean} Show the product's vendor depending on the section setting (optional)
    - media_size: {String} Size of the product image card. Values are "square" and "portrait". Default is "square" (optional)
    - show_full_details: {Boolean} Show the link to full details (optional). Default to hide
    - center_align_text: {Boolean} Center all the text contained inside. Default is to left-align (optional)

    Usage:
    {% render 'product-card', show_vendor: section.settings.show_vendor %}
{% endcomment %}
```

These parameters are all meant to be optional.  For example, when a section is being rendered in its onboarding state there may not be any product passed to the product card snippet.

**`theme-check` throws the following errors because the objects are unidentified in that circumstance:**

```
Missing argument `product_card_product`theme-check(UndefinedObject)
Missing argument `show_full_details`theme-check(UndefinedObject)
Missing argument `center_align_text`theme-check(UndefinedObject)
Missing argument `show_vendor`theme-check(UndefinedObject)
```

## Expected

For "optional" parameters to be recognized as such and not throw an error in cases like this.

One idea could be just a code standard where we prefix optional parameters somehow -  `o_product_card_product` - to have it ignore the `UndefinedObject` check.

**Comment by macournoyer** [comment]
Sounds good for the `o_` prefix 👍  We just need to ignore all objects/variables with a `o_` prefix.

**Comment by macournoyer** [comment]
As discussed in #134, I think a better approach seems to be to give default values the optional variables at the top of the snippet:

```
{% assign optional = optional | default: false %}
```

Now I don't know where to document this... Perhaps just using this in our sample themes will be enough of an example?
