### ISSUE TITLE
High ruby CPU usage

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/theme-check#147]
I installed this within VSCode yesterday and since then my CPU's been going crazy.
It seems theme-check is constantly running and hammering my CPU usage.
![image](https://user-images.githubusercontent.com/18140157/107505328-73f99380-6b94-11eb-80cb-f01fa408a744.png)
![image](https://user-images.githubusercontent.com/18140157/107505350-7a880b00-6b94-11eb-8817-8bd432436f18.png)

**Comment by macournoyer** [comment]
Is this going on even when not editing any files in vscode?

Also, did you reload the vscode window? (Ctrl + Shift + P > Reload Window)

**Comment by ConduciveMammal** [comment]
It is when I'm not directly editing them, so the project files are open with `theme-check` running in the Problems panel, but not from me specifically editing them.

As far restarting, in the Activity Monitor, if I Force Quit `ruby` while VSCode's open, it just restarts instantly with the same CPU usage. If I quit VSCode, the `ruby` process remains, but Force Quitting it keeps it finished.

**Comment by ConduciveMammal** [comment]
The extension seems to have just crashed itself (And CPU flatlined). VSCode is producing this error log:

```
Checking /Users/UserName/Shopify.nosync/ProjectFolder
Found 5235 templates, and 3399 offenses
undefined method `+' for nil:NilClass
/usr/local/Cellar/theme-check/0.2.2/gems/theme-check-0.2.2/lib/theme_check/offense.rb:73:in `end_column'
/usr/local/Cellar/theme-check/0.2.2/gems/theme-check-0.2.2/lib/theme_check/language_server/handler.rb:110:in `range'
/usr/local/Cellar/theme-check/0.2.2/gems/theme-check-0.2.2/lib/theme_check/language_server/handler.rb:81:in `offense_to_diagnostic'
/usr/local/Cellar/theme-check/0.2.2/gems/theme-check-0.2.2/lib/theme_check/language_server/handler.rb:74:in `block in send_diagnostic'
/usr/local/Cellar/theme-check/0.2.2/gems/theme-check-0.2.2/lib/theme_check/language_server/handler.rb:74:in `map'
/usr/local/Cellar/theme-check/0.2.2/gems/theme-check-0.2.2/lib/theme_check/language_server/handler.rb:74:in `send_diagnostic'
/usr/local/Cellar/theme-check/0.2.2/gems/theme-check-0.2.2/lib/theme_check/language_server/handler.rb:58:in `block in send_diagnostics'
/usr/local/Cellar/theme-check/0.2.2/gems/theme-check-0.2.2/lib/theme_check/language_server/handler.rb:56:in `each'
/usr/local/Cellar/theme-check/0.2.2/gems/theme-check-0.2.2/lib/theme_check/language_server/handler.rb:56:in `send_diagnostics'
/usr/local/Cellar/theme-check/0.2.2/gems/theme-check-0.2.2/lib/theme_check/language_server/handler.rb:50:in `analyze_and_send_offenses'
/usr/local/Cellar/theme-check/0.2.2/gems/theme-check-0.2.2/lib/theme_check/language_server/handler.rb:35:in `on_text_document_did_open'
/usr/local/Cellar/theme-check/0.2.2/gems/theme-check-0.2.2/lib/theme_check/language_server/server.rb:89:in `process_request'
/usr/local/Cellar/theme-check/0.2.2/gems/theme-check-0.2.2/lib/theme_check/language_server/server.rb:30:in `block in listen'
/usr/local/Cellar/theme-check/0.2.2/gems/theme-check-0.2.2/lib/theme_check/language_server/server.rb:29:in `loop'
/usr/local/Cellar/theme-check/0.2.2/gems/theme-check-0.2.2/lib/theme_check/language_server/server.rb:29:in `listen'
/usr/local/Cellar/theme-check/0.2.2/gems/theme-check-0.2.2/lib/theme_check/language_server.rb:8:in `start'
/usr/local/Cellar/theme-check/0.2.2/gems/theme-check-0.2.2/exe/theme-check-language-server:11:in `<top (required)>'
/usr/local/bin/theme-check-language-server:6:in `load'
/usr/local/bin/theme-check-language-server:6:in `<main>'
[Error - 2:46:19 PM] Connection to server is erroring. Shutting down server.
[Error - 2:46:19 PM] Connection to server is erroring. Shutting down server.
[Error - 2:46:19 PM] Connection to server is erroring. Shutting down server.
```

It says 5235 templates but that's most definitely not a true number.

**Comment by macournoyer** [comment]
Aaah I think we fixed this in the new upcoming release. Do you have a `node_modules` directory by any chance? Or any other directory w/ lots of .json files.

**Comment by ConduciveMammal** [comment]
Ahh great! I do indeed have `node_modules`. Forever will that folder be the bane of our existence ha!

**Comment by macpham** [comment]
I had high CPU problems because of a `ruby` process too recently, and I had to hard power cycle my laptop. I can't recall which themes I had open, possibly older ones with a lot of files, namely `node_modules` as well.

This doesn't had not happened to me before whilst working on `dawn` theme for weeks now since it doesn't have any `node_modules` to speak of :)

**Comment by macournoyer** [comment]
We now ignore `node_modules` by default: `brew upgrade theme-check`. This should help a lot!

Let me know if you still see high CPU usages.

**Comment by hinogi** [comment]
Still seems to be an issue on linux systems, maybe not in vscode but the host.

**Comment by macournoyer** [comment]
@hinogi can you tell me how many templates theme-check is scanning.

From the bottom pane: Output > Select "Theme Check Language Server" from the dropdown on the right. You should see something like:

```
Checking .
Found X templates, and Y offenses
```

**Comment by ConduciveMammal** [comment]
I seem to be noticing this also.

Only thing showing in Output is:
`Checking /Users/UserName/Shopify.nosync/ProjectRoot/src/theme`

Seeing high `ruby` CPU in Activity Monitor also:
![image](https://user-images.githubusercontent.com/18140157/114402210-82b3f500-9b9b-11eb-9fe1-31a6a1ad731b.png)

**Comment by ConduciveMammal** [comment]
Correction on the above. If I intentionally force quit the `ruby` processes, theme-check obviously crashes and produces the following log, seems to be an issue from `documentLink`.

```
[Error - 2:35:53 PM] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.2.2/dist/extension.js:1:35828)
	at Object.dispose (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.2.2/dist/extension.js:1:116000)
	at w.handleConnectionClosed (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.2.2/dist/extension.js:1:116213)
	at w.handleConnectionClosed (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.2.2/dist/extension.js:1:176601)
	at t (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.2.2/dist/extension.js:1:114302)
	at r.invoke (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.2.2/dist/extension.js:1:37441)
	at o.fire (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.2.2/dist/extension.js:1:38202)
	at Y (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.2.2/dist/extension.js:1:25086)
	at r.invoke (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.2.2/dist/extension.js:1:37441)
	at o.fire (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.2.2/dist/extension.js:1:38202)
	at m.fireClose (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.2.2/dist/extension.js:1:46083)
	at Socket.<anonymous> (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.2.2/dist/extension.js:1:47668)
	at Socket.emit (events.js:327:22)
	at Socket.EventEmitter.emit (domain.js:483:12)
	at Pipe.<anonymous> (net.js:674:12)
```

**Comment by charlespwd** [comment]
Probably another darn slow regex. I should add a suite of tests to prevent against those when I get the time.

**Comment by ConduciveMammal** [comment]
@macournoyer 
Correct, yeah, I'm running `0.7.0`.

**Comment by charlespwd** [comment]
Fix is in 0.7.1. Should be good to go now! 

```
brew update 
brew upgrade theme-check
```

**Comment by ConduciveMammal** [comment]
@charlespwd this seems to have crept back, unfortunately.
Seems to be quite random, and not occurring permanently.

If I use the `Restart Server` option, I momentarily get two `theme-check` processes both at 100+% CPU for about 20 seconds before it returns to just one.

![image](https://user-images.githubusercontent.com/18140157/118634413-67f02400-b7ca-11eb-8b69-7f703551096e.png)

**Comment by macournoyer** [comment]
Since 0.8.3, it should throw an error if any of the checks are taking more than 5 sec to run. So it doesn't seem this is because of a single check hanging.

Do you see anything special in the Output pane? Is it constantly outputting "Checking ... Found X templates ..."?

I'll work on adding tracing logs so we can get more info.

**Comment by ConduciveMammal** [comment]
Hmmm seems to have happened again, although nothing in the Output pane. The only thing I did was open a JS file outside of the theme root.

![image](https://user-images.githubusercontent.com/18140157/118660127-d098ca00-b7e5-11eb-9c74-a1dd50c5830c.png)

**Comment by macournoyer** [comment]
The VS Code plugin will now only scan files that have changed. It should be a lot faster, and consume less CPU time 🤞
