### ISSUE TITLE
Implement InMemoryFilesystem Liquid::Template.file_system to work with InMemoryStorage

### ISSUE THREAD

**Issue by charlespwd** [Shopify/theme-check#152]
See https://github.com/Shopify/liquid/blob/3358a892f28845f3d154177106a8a56eb65c05ca/lib/liquid/file_system.rb#L4-L22

Right now render and include won't work with InMemoryStorage.

**Comment by macournoyer** [comment]
But we don't actually render the partials, only parse the templates. I can't figure out why we would need this. Did you get an error?

**Comment by charlespwd** [comment]
Nope nvm just reading code poorly 🙃 Making assumptions that turned out wrong. So much learning :p
