### ISSUE TITLE
Recommend removing snippets that are only used in one place

### ISSUE THREAD

**Issue by macournoyer** [Shopify/theme-check#158]
We don't want to encourage the use of snippets, particularly as "functions"

**Comment by kilgore5** [comment]
Curious about the reasoning behind this?

**Comment by macournoyer** [comment]
Snippets are mainly for sharing code between templates. But if it's only used in one place, it is not shared.

Do you have a use-case where it make sense to have a snippet only used in one place?

**Comment by charlespwd** [comment]
It could be argued that it's to pull the logic out of a huge file dump. As a way to componentize / make the theme easier to read.

**Comment by five23** [comment]
I think developers like myself didn't really understand the cost in build times and added complexity in linting/checking when we modularised so many things into snippets. Also, coming from Magento, we had a tendency to think of everything like a MVC app. On down the rabbit hole we went (*cough* slate *cough*). I personally noticed this pathology in my client's themes only recently and have started moving snippet logic back into its calling files.

Meanwhile, in a fresh branch, `theme new`.

**Comment by kilgore5** [comment]
Agree 100% with @charlespwd ... Liquid is verbose and unwieldy enough as it is. It's difficult to read and reason about code with so many indention levels.

While I also agree with @five23 that there is added build time and complexity, unless I hear about a severe performance hit from snippets alone (which is what I was originally curious about), then I'll stick with snippets even when used only once.

**Comment by macournoyer** [comment]
Yeah good points. Thanks everyone! The performance impact is negligible.

I'll close this as we don't really provide a better way to solve this yet.
