### ISSUE TITLE
Lint/prettify JSON

### ISSUE THREAD

**Issue by macournoyer** [Shopify/theme-check#16]
`{% schema %}` & all `.json` files must contain valid JSON.

See https://shopify.dev/docs/themes/sections#using-section-schema-tags.

We currently parse the JSON in Ruby to check for syntax error. But it would be nice to pass it through a real JSON linter/formatter that would give use line number error and better error messages.

**Comment by josheche** [comment]
Is this still on anyone's radar? Linting and prettification of section schema and .json based schema files would be valuable to my team.

**Comment by macournoyer** [comment]
Hey Josh! Not at the moment. But we do want to add more checks and validation to the schemas eventually.
