### ISSUE TITLE
VSCode doesn't seem to recognise fixes to code before save.

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/theme-check#171]
![image](https://user-images.githubusercontent.com/18140157/108529815-ca6d7d00-72cc-11eb-9769-2fe2d4d04bfe.png)
I corrected this issue but `theme-check` doesn't seem to update until I hit save.

I'm not sure if this is expected behaviour or not, I notice ESLint and others seem to update as soon as the issue's fixed without needing to save.

**Comment by macournoyer** [comment]
Yes, it's the expected behaviour for now. We need the file on disk. But there's probably a way around it. That's a good idea 👍
