### ISSUE TITLE
Shopify Checkout variables are marked as undefined

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/theme-check#184]
Just been working on a Checkout layout and theme-check believes the Shopify Checkout variables are undefined.
Not a big issue, but might be worth adding them to the defs.

![image](https://user-images.githubusercontent.com/18140157/109506866-099e8980-7a96-11eb-862e-7ef4d03db878.png)

**Comment by charlespwd** [comment]
We already [support those](https://github.com/Shopify/theme-check/blob/master/data/shopify_liquid/plus_objects.yml) 🤔. But we only do support them in files of path `layout/checkout.liquid` ([source](https://github.com/Shopify/theme-check/blob/master/lib/theme_check/checks/undefined_object.rb#L119-L123)).

Possible that a `.theme-check.yml` is missing or that this file is not of path `layout/checkout.liquid`?

**Comment by macournoyer** [comment]
Ah yeah nice catch! Could it be that those are in a snippet? We use the filename to detect if plus objects are available: https://github.com/Shopify/theme-check/blob/master/lib/theme_check/checks/undefined_object.rb#L119

**Comment by charlespwd** [comment]
[Snippets are not allowed in `checkout.liquid`, though.](https://shopify.dev/docs/themes/theme-templates/checkout-liquid#TOCAccordion:~:text=For%20merchants%20on%20Shopify%20Plus%2C%20the,checkout%20process%20includes%20the%20following%20steps%3A)
