### ISSUE TITLE
Threshold for nested snippet limit?

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/theme-check#187]
What's the threshold for "Too many nested snippets"? How many is too many?
![image](https://user-images.githubusercontent.com/18140157/110362136-d2e9e580-8038-11eb-8345-80f6d8fad510.png)

**Comment by charlespwd** [comment]
We should work on our documentation. [The default value is 2.](https://github.com/Shopify/theme-check/blob/master/lib/theme_check/checks/nested_snippet.rb#L22-L23)

You should be able override this in theme-check.yml by setting the max_nesting_level value.

```yaml
NestedSnippet:
  max_nesting_level: 10
```

**Comment by ConduciveMammal** [comment]
Perfect, thanks!
