### ISSUE TITLE
CLI exit codes

### ISSUE THREAD

**Issue by charlespwd** [Shopify/theme-check#188]
The CLI should exit 0 if none of the failing checks are of type `:error`.

**Comment by macournoyer** [comment]
Should maybe be an option? strict mode?

**Comment by charlespwd** [comment]
~I'm pretty sure this is standard in all linters out there. This would be more about being consistent with the ecosystem.~ This is how the JS ecosystem does it. Rubocop has a `--fail-level error` option.

But maybe there are ways to do something better. A bit like eslint is doing with the max warnings flag.

https://eslint.org/docs/user-guide/command-line-interface#exit-codes
https://palantir.github.io/tslint/usage/cli/
https://prettier.io/docs/en/cli.html#exit-codes

The convention seems to be around 1 = error found and 2 = problem with `$TOOL`.

**Comment by macournoyer** [comment]
They all look the same to me, eslint has `--max-warnings`. Looks like a different way of saying `--fail-level` 🤷‍♂️

**Comment by charlespwd** [comment]
Well they are kind of different, the argument that `--fail-level` takes is a `level` (error, warning, info) whereas `--max-warnings` is a number - the maximum number of warnings allowed until the build becomes a fail.
