### ISSUE TITLE
Implement Size Limit Checks

### ISSUE THREAD

**Issue by charlespwd** [Shopify/theme-check#189]
This would be a check of type :performance.

For server rendered pages, it is an anti-pattern to execute large JavaScript bundles on every navigated page. However, that doesn't mean they don't have a reason to exist. Arguably, chat widgets are mini apps embedded inside web pages. Designing such an app with server rendered updates would be absurd.

On the flip side, if 10% of the users interact with the chat widget, the other 90% should not have to execute the entire bundle on every page load.

The natural solution to this problem is to implement the chat widget using the [import on interaction pattern](https://addyosmani.com/blog/import-on-interaction).

So, how can we implement a rule that encourages the use of this pattern while still enabling large bundles inside a theme?

Some ideas:
* ~Static size checks~ _Can't tell if loaded on interaction or not. Prevents the accepted use of large JS bundles loaded on interaction_.
* Static resource import check / aka find all script tags on the page, find their brotli size throw above configurable threshold. To be explored. What about remote assets? How can we figure out if the asset is being used? Scanning for `asset_url` filters?

**Comment by macournoyer** [comment]
Just an idea: We could fetch & discard the remote resources just to get their sizes (if you set `Accept-Encoding: br` is will take care of the compression)? And cache it locally perhaps?
