### ISSUE TITLE
Does `ignore` config accept regex?

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/theme-check#191]
I'm trying to ignore all filetypes with the extensions `(css|scss|js).liquid` but can't seem to get it to recognise the Regex.
```yml
ignore:
  - /*/**/[a-z0-9_\.-]+.(css|scss|js).liquid
 ```
I also tried with asterisk wildcards:

```yml
ignore:
  - /*/**/*.(css|scss|js).liquid
```

Secondly, what's the "root" of the ignore when using non-default `root` paths?
For example, I'm using:
```yml
root: src/theme
```

So in my `ignore`'s, would the root be `src/theme/assets/` or just `assets/`?

**Comment by macournoyer** [comment]
It is based on [`fnmatch`](https://man7.org/linux/man-pages/man3/fnmatch.3.html), so it behaves like [glob](https://man7.org/linux/man-pages/man7/glob.7.html).

You could do:

```
ignore:
  - assets/*.css.liquid
  - assets/*.scss.liquid
  - assets/*.js.liquid
```

Maybe you could use `assets/*.{css,scss,js}.liquid` instead, but I'm not sure.

> So in my `ignore`'s, would the root be `src/theme/assets/` or just `assets/`?

The root would be `src/theme`. Ignores are matches relative to that.

Let me know if that's not clear or doesn't work.

**Comment by ConduciveMammal** [comment]
Thanks for that!
Unfortunately `assets/*.{css,scss,js}.liquid` doesn't seem to work.

For other's reference here's my winning set:
```yml
ignore:
  - assets/*.css.liquid
  - assets/*.min.css.liquid
  - assets/*.js.liquid
  - assets/*.min.js.liquid
  - assets/*.scss.liquid
  - assets/*.min.scss.liquid
```
