### ISSUE TITLE
echo tag seems to interfere with UnusedAssign

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/theme-check#218]
So after converting a block of Liquid to the new `liquid` and `echo` tag, theme-check seems to think my variables are unused.

![image](https://user-images.githubusercontent.com/18140157/111781097-1271c680-88b0-11eb-9e4f-5270ccdc2396.png)

**Comment by charlespwd** [comment]
GH improperly closed this. We still need to bump the liquid dependency in this repo. Waiting on liquid gem publish.

**Comment by macournoyer** [comment]
PR to release Liquid: https://github.com/Shopify/liquid/pull/1417
