### ISSUE TITLE
Output results as JSON

### ISSUE THREAD

**Issue by pgrimaud** [Shopify/theme-check#220]
Hello,

First, great linter! I love it.

Then, I could not found any way to output results as raw format like JSON. 
It could be useful for CI implementation. e.g. to create dedicated issues, PR or other stuff.

What do you think about it?

**Comment by charlespwd** [comment]
I love it. Definitely should do that.

**Comment by pgrimaud** [comment]
Maybe with `-o` option?

Something like this `theme-check -o output.json` or/and directly in `.theme-check.yml` file?

**Comment by charlespwd** [comment]
Yeah -o feels better to me. This way you could have your CI output different from the one you might run locally.

**Comment by pgrimaud** [comment]
> Yeah -o feels better to me. This way you could have your CI output different from the one you might run locally.

Totally agreed. Do you need some help to do it?

I am not very familiar with Ruby. But it can be the opportunity to improve myself. Unless it becomes a priority feature from your side?

**Comment by charlespwd** [comment]
PRs are absolutely welcome! If you want to take a stab at it, by all means! Let me know if you need pointers. 

Quick context: you're probably going to need to play with the following files:

- https://github.com/Shopify/theme-check/blob/master/lib/theme_check/cli.rb
- https://github.com/Shopify/theme-check/blob/master/lib/theme_check/printer.rb

And either make the printer accept formats, or make multiple printers, one per format type. 

This is probably where you'd need to handle the switching: 
- https://github.com/Shopify/theme-check/blob/master/lib/theme_check/cli.rb#L115
