### ISSUE TITLE
Form field property incorrectly seen as undefined object.

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/theme-check#228]
Theme Check seems to incorrectly see form field properties as undefined objects. I believe due to the lack of quotes.

![image](https://user-images.githubusercontent.com/18140157/112302298-d0bb9400-8c92-11eb-96b2-e6a31f273629.png)

According to [Shopify documentation](https://shopify.dev/tutorials/customize-theme-add-fields-to-your-contact-form#types-of-form-fields), this is actually the correct way to name form fields, as per the below example:

```html
<label for="ContactFormBirthday">Birthday</label>
<input
  type="text"
  id="ContactFormBirthday"
  name="contact[Birthday]"
  placeholder="Birthday"
/>
```

Interestingly, it seems to accept `contact[email]` perfectly fine. So perhaps I've done this wrong.

![image](https://user-images.githubusercontent.com/18140157/112303563-52f88800-8c94-11eb-9cc1-4deeb97b0c7b.png)

**Comment by charlespwd** [comment]
Yeah the quotes are necessary because otherwise the access is ambiguous. Is it the _variable_ name or the _string_ name? 

```liquid|
<!-- oops -->
{% assign name = "Mark" %}
{% if form[name] %}...{% endif %}

<!-- OK -->
{% if form["name"] %}...{% endif %}
{% if form.name %}...{% endif %}
```

Liquid _is_ very lax though and may try to use form.name in the case where the assign isn't defined but it's not recommended to rely on that. Best to use the quotes or the dot property access.

**Comment by ConduciveMammal** [comment]
Gotcha! So even though it works from a systematic point of view, it's recommended to use quotes around the form property names?

**Comment by charlespwd** [comment]
Yep!
