### ISSUE TITLE
Snippet Document Links don't account for root config

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/theme-check#231]
I was super psyched for this update. I was actually planning on creating an extension to do exactly this.

Regrettably, there seems to be a small issue where it doesn't account for the `root` config setting, meaning the snippets directory is incorrect.

`root: src/theme`

![image](https://user-images.githubusercontent.com/18140157/112380807-bceb4e80-8ce1-11eb-8167-1d8ef2c379ae.png)
Censored part is the Project Root directory.

**Comment by charlespwd** [comment]
Right! Thanks for flagging, we'll fix!
