### ISSUE TITLE
HTML comment incorrectly labelled as "Unknown tag".

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/theme-check#251]
When placing HTML comments inside of a Liquid statement, VSCode's Problems panel incorrectly states the comment is an unknown tag, whilst also not underlining the erroneous code like other errors and warnings.

Incorrect line number given also, although I believe this is Liquid error, rather than a `theme-check` error.

```liquid
{% if enableFilter %}
  <!--begin-bc-sf-filter-css-->
    {% render 'bc-sf-filter-style' %}
  <!--end-bc-sf-filter-css-->
{% endif %}
```
![image](https://user-images.githubusercontent.com/18140157/114040318-68b4a280-987b-11eb-956e-29e988414f83.png)

**Comment by charlespwd** [comment]
Debugged out of band. Not a bug.
