### ISSUE TITLE
Add system translation for spam_detection.disclaimer_html

### ISSUE THREAD

**Issue by gideonb** [Shopify/theme-check#265]
### Context
The Recaptcha V3 update added a legal requirement for Recaptcha-protected contact forms to display a link to Recaptcha's terms and conditions.  On stores with a contact form section on the homepage, this would add a sticky Recaptcha logo to the bottom corner of the page, often blocking chat widgets or other features. 

Needless to say, the legally required sticky blue recycling logo is not a popular feature.  

The fix is to add a translation to the contact form that cleverly injects a link to the terms and conditions.  That code is:
```{{ 'shopify.online_store.spam_detection.disclaimer_html' | t }}```

When that code is present inside the `{% form %}` object the sticky recycling logo goes away.  

Here's a docs link if you don't want to take my word for it:
https://shopify.dev/docs/themes/recaptcha-v3

### Issue
Theme-check does not recognize `shopify.online_store.spam_detection.disclaimer_html` to be a system translation so it throws the following error:
![image](https://user-images.githubusercontent.com/299520/115319486-ca56f580-a134-11eb-98d6-decabea9e91f.png)

**Comment by charlespwd** [comment]
I absolutely take your words for it.

We don't have a good solution to sync new keys as they come in. Will add!

**Comment by thagxt** [comment]
@charlespwd  Not working for me:

<img width="1457" alt="Screenshot 2024-02-14 at 13 23 53" src="https://github.com/Shopify/theme-check/assets/7128602/8448becc-4ae7-4e72-b3c5-5dc2663af0b9">
