### ISSUE TITLE
Can Liquid-enabled images be ignored from RemoteAsset checks?

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/theme-check#306]
I use metafields quite a lot to serve user-uploaded images on product pages etc. Until Sections Everywhere is actually a thing, this is the **only** way to add them.

Because of that, can these image assets be ignored in the `RemoteAsset` check?

```liquid
<img
  src="{{ benefit_meta_graphic.cloudinary_src | append: 'w_135,h_135' }}"
  srcset="{{ benefit_meta_graphic.cloudinary_src | append: 'w_135,h_135' }} 1x, {{ benefit_meta_graphic.cloudinary_src | append: 'w_135,h_135,dpr_2.0' }} 2x"
  height="135"
  width="135"
  alt="{{ benefit_meta_graphic.alt }}" />
```

**Comment by macournoyer** [comment]
Ah user-uploaded images is good use case! No way to make those go through our CDN afaik.

We should be able to ignore those I think. Any ideas on this @charlespwd ?
