### ISSUE TITLE
Add check to deprecate lazysizes.js (and bgsizes.js)

### ISSUE THREAD

**Issue by colinbendell** [Shopify/theme-check#314]
Using lazysizes.js should be flagged as an error. This includes any of the common javascript libraries (lazysizes.js, bgsizes.js) as well as any of the implementations. This includes: `class=lazyload`, `data-srcset=`, `data-sizses=` and worst of all `sizes=auto`.

Uses of bgsizes for background images responsive images should be encouraged to use the css `imageset` attribute. (bgsizes is a common lazysizes plugin)

**Comment by andershagbard** [comment]
I believe it's a bit too early to recommend not using JS lazyloading.

Currently `loading="lazy"` has [73.98% support](https://caniuse.com/loading-lazy-attr).

**Comment by macournoyer** [comment]
Good point @andershagbard !

I think what we should do is extract the lazysizes check out of the current `ImgLazyLoading`, and into a new `DeprecateLazysizes`.

So you could disable `DeprecateLazysizes` without disabling the recommendation to use the new `loading=lazy`.
