### ISSUE TITLE
ImgWidthAndHeight check always returns line 0 when run in core

### ISSUE THREAD

**Issue by catlee** [Shopify/theme-check#363]
When theme-check is run in core as part of submitting a new draft of a theme app extension, the line numbers for the ImgWidthAndHeight are always reported as line 0.

When theme-check is run locally, the correct line numbers are reported. Other checks don't seem to have this problem.

![](https://user-images.githubusercontent.com/54458/125498278-275bb263-c11d-4b38-9751-cbcbcf9aad15.png)

**Comment by catlee** [comment]
This should be fixed by nokogiri 1.12, which was released on august 2nd.

We should wait for core to update nokogiri first before bumping our requirements.

**Comment by charlespwd** [comment]
Hey @catlee, looks like we no longer depend on nokogumbo in here. Maybe worth revisiting?

**Comment by catlee** [comment]
Yup, this should be getting fixed up in core shortly.

**Comment by catlee** [comment]
This should be fixed in core now.
