### ISSUE TITLE
Is there an eslint plugin?

### ISSUE THREAD

**Issue by mattjis** [Shopify/theme-check#370]
My code editor "Nova" doesn't have a Shopify theme check extension. 

Is there an eslint extend I could use e.g `plugin:@shopify/esnext`?

**Comment by macournoyer** [comment]
Never heard of Nova, but if it has a LSP client plugin, you should be able to follow instructions on https://github.com/Shopify/theme-check/wiki to set it up.

eslint is for linting JS files, theme checks is for linting .liquid & .json files inside Shopify themes.
