### ISSUE TITLE
theme-check error while executing on Windows 10

### ISSUE THREAD

**Issue by m-atek** [Shopify/theme-check#371]
Hi, I have an issue running theme-check on Windows 10. I get multiple lines like this one:

`#!C:/Ruby30-x64/bin/ruby.exe
'#!C:' is not recognized as an internal or external command,
operable program or batch file.
`

I have C:/Ruby30-x64/bin directory in my PATH. I could not find solution online.

Thanks in advance.

**Comment by ADTC** [comment]
For some reason, the `.bat` files are copies of the shell scripts, and then there are `.bat.bat` files which are the actual batch files.

![image](https://user-images.githubusercontent.com/6047296/129634893-eb4eebde-b6c1-48d4-b0d7-294baee16c27.png)

If you want to fix this in your local installation, delete the `.bat` files and rename the `.bat.bat` files to `.bat`:

![image](https://user-images.githubusercontent.com/6047296/129635040-083eeb24-f47a-4751-aaeb-dd3f8ac85767.png)

**Comment by charlespwd** [comment]
> For some reason, the .bat files are copies of the shell scripts, and then there are .bat.bat files which are the actual batch files.

![image](https://user-images.githubusercontent.com/4990691/129744397-fb439b6f-6736-47d8-9cfe-e16b151f9b9c.png)

I'll have to look into this. Looks like our gemspec is doing funky stuff.
