### ISSUE TITLE
Provide config to ignore paths in detected issues

### ISSUE THREAD

**Issue by isAdrisal** [Shopify/theme-check#373]
Hi all,

This proposal is for theme-check to provide a config option to ignore rule failures/warnings based on the `offence`, in addition to the detection path (current functionality).

## Explanation
To illustrate the point:

```yml
root: src

MissingTemplate:
  ignore:
    - snippets/icon-*
```

The above `config` will ignore the `MissingTemplate` rule in any file that matches the path, `snippets/icon-*`.

What I am proposing is to provide a way to ignore the `MissingTemplate` rule for any offences that relate to a missing file that matches the path `snippets/icon-*`.

For prior art, this new proposed behaviour is similar to the way in which `ignore` works for rules within ESLint. For example, a similar rule in ESLint is `import/no-unresolved`:

```json
"rules": {
  "import/no-unresolved": [
    "error",
    {
      "ignore": ["^react$"]
    }
  ],
}
```

The above ESLint config will ignore the `import/no-unresolved` rule for any unresolved imports of `react`. However, ESLint will continue to check all eligible files (`.js`, `.json`, `.jsx`) for this rule.

## Use case
The use case for this offence-based `ignore` is very common in other linting tools, and will likely be equally popular for Liquid files.

Using the `MissingTemplate` example, a developer may want to have this rule enabled to prevent against including a missing snippet/section/template, but there may be a set of files (such as icons) that are added to the snippets folder as part of a build process. In this case, the developer can make the conscious decision to suppress warnings/errors/suggestions for missing icon files.

**Comment by macournoyer** [comment]
> What I am proposing is to provide a way to ignore the `MissingTemplate` rule for any offences that relate to a missing file that matches the path `snippets/icon-*`.

Hey Adriano! I'm not sure I get what you mean, because this looks to me exactly like what we provide already. Could you give me an example of how this particular use case could look in the config file?

**Comment by isAdrisal** [comment]
Hey @macournoyer, no problem! I've included a couple of screenshots below.

**Current behaviour:**
The `MissingTemplate` rule is detected in `templates/page.style-guide.liquid`. The `ignore` value here is preventing the rule from being detected within a file matching `snippets/icon-*` — therefore having no effect on `page.style-guide.liquid`.

<img width="700" alt="Screen Shot 2021-07-21 at 11 12 25 am" src="https://user-images.githubusercontent.com/29012873/126415175-0490f528-0866-4160-8e3f-567d1175c161.png">

**Proposed addition:**
The `MissingTemplate` rule is checked in `templates/page.style-guide.liquid`, but ignored if the detected offence relates to a file matching `snippets/icon-*`.

<img width="700" alt="Screen Shot 2021-07-21 at 11 19 40 am" src="https://user-images.githubusercontent.com/29012873/126415485-7d83e2a8-4176-48a0-b34b-939887cd9a25.png">

Providing the ability to use a regular expression as a value in `ignoreOffence` will help to generalise the feature across all types of rules, where the regular expression is evaluated against the entire offence message, eg. `'snippets/icon-account.liquid' is not found`.

For now, the workaround would appear to be to write a custom rule based on MissingTemplate that hard-codes this ignore logic, making it less portable across projects.

**Comment by macournoyer** [comment]
Oooh I get it now! Thanks for clarifying. That make sense.

This is pretty specific to `MissingTemplate`, what do you think about:

```
MissingTemplate:
  ignore_missing:
    - snippets/icon-*
```

Just curious, why do you want to ignore this particular error? Seems like rendering a missing file is a pretty important error.

**Comment by isAdrisal** [comment]
No problem! `ignore_missing` would work for me.

This particular theme has a webpack build step that among other things, moves `.svg` icon files from a folder in `src` and turns them into `.liquid` equivalents in `dist/snippets`.

Similarly, the build step dynamically creates `script-tags.liquid` and `style-tags.liquid` snippets using compiled assets that are layout/template specific. These snippets don't exist in the `src` directory, so currently show a warning in theme-check.
