### ISSUE TITLE
Emacs Configuration

### ISSUE THREAD

**Issue by trev-dev** [Shopify/theme-check#379]
Hello!

I cannot do a merge request on a wiki, but I have a working emacs configuration for use with `lsp-mode` and `web-mode`. A person does not have to use web-mode. They could also use html-mode or whatever other major syntax mode they decide is most appropriate for liquid.

Here it is:

```elisp
;; Shopify template lsp with theme-check
(with-eval-after-load 'lsp-mode
  (add-to-list 'lsp-language-id-configuration
    '(web-mode . "\\.liquid\\'"))

  (lsp-register-client
    (make-lsp-client :new-connection (lsp-stdio-connection "theme-check-language-server")
                     :activation-fn (lsp-activate-on "\\.liquid\\'")
                     :server-id 'theme-check)))
```

**Comment by charlespwd** [comment]
Thank you! Added!
