### ISSUE TITLE
Remove nokogumbo dependency

### ISSUE THREAD

**Issue by rafaelfranca** [Shopify/theme-check#390]
[Nokogiri 1.12 included the nokogumbo HTML5 parser](https://github.com/sparklemotion/nokogiri/releases/tag/v1.12.0). Because of that, nokobumbo is now deprecated and show a warning when used if nokogiri is also present, which is always true in every Rails application.

We should remove the nokogumbo dependency and change it to nokogiri >= 1.12.

**Comment by macournoyer** [comment]
FIxed in #391
