### ISSUE TITLE
Don't block the language server when running analyze.

### ISSUE THREAD

**Issue by charlespwd** [Shopify/theme-check#424]
Analyze can take 15 seconds to run on Windows. Since our language server's loop is synchronous, this means you won't get any kind of completion until the linter is done linting. We should look into making it a proper server (or just spawn the analyze in some kind of background thread).

@macournoyer knows a thing or two about server loops :P We should ask him for pointers.

**Comment by macournoyer** [comment]
I thought about doing it a couple months ago. But wasn't clear to me how to return responses when processing async? Does LSP support some sort of pipelining, eg.:

```
request 1
request 2
response 2
response 1
```

As opposed to what we do now, always in sequence:

```
request 1
response 1
request 2
response 2
```

**Comment by charlespwd** [comment]
IIRC response needs to be returned sync but notifications don't (diagnostics are notifications).

**Comment by macournoyer** [comment]
Oh that's perfect then!
