### ISSUE TITLE
Error when running `shopify theme check`

### ISSUE THREAD

**Issue by zulufucxs** [Shopify/theme-check#440]
From the terminal:

> Checking . ...
> Exception while running `PaginationSize#after_document`:
> ```
> NoMethodError: undefined method `empty?' for nil:NilClass
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.5.0/lib/theme_check/checks/pagination_size.rb:58:in `get_setting_default_value'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.5.0/lib/theme_check/checks/pagination_size.rb:44:in `block in after_document'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.5.0/lib/theme_check/checks/pagination_size.rb:40:in `each_pair'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.5.0/lib/theme_check/checks/pagination_size.rb:40:in `after_document'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.5.0/lib/theme_check/checks.rb:42:in `block in call_check_method'
>   /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/timeout.rb:97:in `block in timeout'
>   /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/timeout.rb:35:in `block in catch'
>   /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/timeout.rb:35:in `catch'
>   /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/timeout.rb:35:in `catch'
>   /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/timeout.rb:112:in `timeout'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.5.0/lib/theme_check/checks.rb:41:in `call_check_method'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.5.0/lib/theme_check/checks.rb:11:in `block in call'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.5.0/lib/theme_check/checks.rb:10:in `each'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.5.0/lib/theme_check/checks.rb:10:in `call'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.5.0/lib/theme_check/visitor.rb:35:in `call_checks'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.5.0/lib/theme_check/visitor.rb:26:in `visit'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.5.0/lib/theme_check/visitor.rb:12:in `visit_template'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.5.0/lib/theme_check/analyzer.rb:39:in `block (2 levels) in analyze_theme'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.5.0/lib/theme_check/analyzer.rb:38:in `each'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.5.0/lib/theme_check/analyzer.rb:38:in `block in analyze_theme'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.5.0/lib/theme_check.rb:57:in `with_liquid_c_disabled'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.5.0/lib/theme_check/analyzer.rb:37:in `analyze_theme'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.5.0/lib/theme_check/cli.rb:183:in `check'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.5.0/lib/theme_check/cli.rb:114:in `run!'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.5.0/lib/theme_check/cli.rb:118:in `run'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/project_types/theme/commands/check.rb:25:in `call'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/sub_command.rb:13:in `call'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/command.rb:19:in `call'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/executor.rb:15:in `call'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/entry_point.rb:24:in `block in call'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/monorail.rb:32:in `log'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/entry_point.rb:23:in `call'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/bin/shopify:33:in `block in <top (required)>'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
>   /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/bin/shopify:32:in `<top (required)>'
>   /usr/local/bin/shopify:6:in `load'
>   /usr/local/bin/shopify:6:in `<main>'
> ```
> 
> Template: `sections/main-blog.liquid`
> Node: `Liquid::Document`
> Markup:
> ```
> 
> ```
> Check options: `{:min_size=>1, :max_size=>50}
> `
> Theme Check Version: 1.5.0
> Ruby Version: 3.0.2
> Platform: x86_64-darwin20
> Muffin mode: activated
> 
> ------------------------

**Comment by charlespwd** [comment]
Fixed in Theme-Check v1.5.1
