### ISSUE TITLE
Windows path gives invalid argument for this code line

### ISSUE THREAD

**Issue by ADTC** [Shopify/theme-check#464]
https://github.com/Shopify/theme-check/blob/831cfd6ce7a8a72370e0c62e6ca8a5fe9dc805f6/lib/theme_check/file_system_storage.rb#L51-L56

It seems this line doesn't play nice with Windows paths (with spaces?).

```
Invalid argument - /c:/Users/ADTC/Downloads/Folder Name Example/theme-folder
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/theme-check-1.4.0/lib/theme_check/file_system_storage.rb:52:in `glob'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/theme-check-1.4.0/lib/theme_check/file_system_storage.rb:52:in `glob'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/theme-check-1.4.0/lib/theme_check/file_system_storage.rb:52:in `glob'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/theme-check-1.4.0/lib/theme_check/file_system_storage.rb:30:in `files'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/theme-check-1.4.0/lib/theme_check/language_server/handler.rb:91:in `in_memory_storage'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/theme-check-1.4.0/lib/theme_check/language_server/handler.rb:33:in `on_initialize'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:107:in `process_request'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:36:in `block in listen'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:35:in `loop'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:35:in `listen'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/theme-check-1.4.0/lib/theme_check/language_server.rb:26:in `start'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/theme-check-1.4.0/exe/theme-check-language-server:10:in `<top (required)>'
C:/Ruby27-x64/bin/theme-check-language-server:23:in `load'
C:/Ruby27-x64/bin/theme-check-language-server:23:in `<main>'
[Error - 11:38:58 AM] Connection to server got closed. Server will not be restarted.
```
Note, this happened in the Shopify Liquid extension in VS Code. The server crashed 5 times in under 3 minutes, and hence wouldn't be restarted anymore.

**Comment by ADTC** [comment]
@charlespwd it looks like this was reported before in #413 and you fixed it in #415 but I'm not sure which theme-check version it will be released on.

I'm also not sure why my theme-check version is only 1.4.0 (it was updated together with Shopify CLI which is at version 2.4.0 now).

**Comment by ADTC** [comment]
I ran `gem update theme-check` to manually update it to 1.7.0 and it appears the error has been resolved.

(Now I'm not even sure if updating Shopify CLI also updates theme-check or not.)

**Comment by charlespwd** [comment]
@ADTC, yea it unfortunately does not. It _eventually_ makes it there but the release process is a bit slower. In the meantime the easiest way to have a newer version of theme-check in the shopify-cli gem is to reinstall the gem. That will reinstall it with the latest version of theme-check. 

Otherwise the shopify-cli gem dependency of `theme-check ~> 1.2` is satisfied by 1.4 and doesn't update automatically.
