### ISSUE TITLE
Please release new versions officially

### ISSUE THREAD

**Issue by lorand-horvath** [Shopify/theme-check#488]
Github has recently changed the way it lists releases, so unless it's an official release, we can't find it here anymore https://github.com/Shopify/theme-check/releases

We can find the latest versions under the tags section though https://github.com/Shopify/theme-check/tags , but it would be preferable to see them officially released in the releases section, as one would expect.

**Comment by charlespwd** [comment]
Should do that indeed. I'm adding that to our release process. Thanks for bringing it up!
