### ISSUE TITLE
Add support for new `image_tag` attribute and additional filters

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/theme-check#513]
Shopify recently released an upgraded `image_tag` HTML filter for responsive images.
Could support for - and possible recommendation of - this tag be added to `theme-check`?

![image](https://user-images.githubusercontent.com/18140157/143486054-c65f9999-11e6-40f9-9673-47c23c3ed572.png)

https://shopify.dev/api/liquid/filters/html-filters#image_tag

**Comment by charlespwd** [comment]
It's already added. Just not released yet 🙃 

https://github.com/Shopify/theme-check/pull/501

Coming soon with the Code Actions :)

**Comment by charlespwd** [comment]
(In 1.9.0, will make a public announcement once shopify-cli merges & releases the changes. You can use it now if you installed theme-check directly and not through the CLI.)
