### ISSUE TITLE
shopifyLiquid.languageServerPath value

### ISSUE THREAD

**Issue by thdoan** [Shopify/theme-check#534]
On a typical Mac installation with `shopify-cli` installed via brew, what should the value of `shopifyLiquid.languageServerPath` be in the VS Code settings?

**Comment by charlespwd** [comment]
`shopifyLiquid.languageServerPath` is for the `theme-check-language-server` executable that is provided from installing theme-check directly (either via `brew install theme-check` or `gem install theme-check`)

In your case, what you want is `shopifyLiquid.shopifyCLIPath` and it would be the output of the following command by default:

```
which shopify-cli
```
