### ISSUE TITLE
Metafield filters are marked as unknown filter

### ISSUE THREAD

**Issue by vfxjohow** [Shopify/theme-check#543]
Hi!

Just wanted to let you know that the metafield filters like metafield_text are throwing an error as unknown filter. As I know they are not depreciated right? If it is valid to use them it would be nice to add them to the linter.

Best regards,

Vinzenz

**Comment by charlespwd** [comment]
:see_no_evil: New feature didn't make it in theme-check. I'll add 'em. Thanks for reporting :)
