### ISSUE TITLE
Ensure <head> and <body> tags are closed in themes

### ISSUE THREAD

**Issue by catlee** [Shopify/theme-check#584]
We've noticed that sometimes app embeds fail to inject into a theme because the theme is missing proper `</head>` and/or `</body>` tags.

Can we add a check for layout files that these tags are properly closed?

**Comment by lukeh-shopify** [comment]
Looks to be resolved in the latest theme check

<img width="821" alt="image" src="https://github.com/user-attachments/assets/241a3c24-a954-49c8-8bff-e0c7b3be0254">

<img width="882" alt="image" src="https://github.com/user-attachments/assets/66c3dc16-9d3e-44e7-ac86-015d54e2c756">
