### ISSUE TITLE
`app` object unrecognized in `:theme_app_extension` config

### ISSUE THREAD

**Issue by mmorissette** [Shopify/theme-check#592]
Support for the new `app` liquid object was added as part of https://github.com/Shopify/theme-check/pull/566. However running theme-check with the theme-app-extension config still reports an error.

```
➜  theme-extension git:(main) ✗ theme-check -C :theme_app_extension
Checking . ...

blocks/hello.liquid:7: error: UndefinedObject: Undefined object `app`.
	{{ app.metafields.features.test }}
	  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Same happens when running from shopify CLI
```
➜  theme-extension git:(main) ✗ shopify extension check
Checking . ...

blocks/hello.liquid:7: error: UndefinedObject: Undefined object `app`.
	{{ app.metafields.features.test }}
	  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Unsure if the problem is with the implementation of support for `app` object or with loading the correct config from the command line.

**Comment by mgmanzella** [comment]
#566 wasn't live in production until we shipped [v1.10.3](https://github.com/Shopify/theme-check/releases/tag/v1.10.3) of theme-check today. this version of theme-check is now available in [shopify-cli 2.19.0](https://github.com/Shopify/shopify-cli/releases/tag/v2.19.0)

the latest version of theme-check appears to fix this linting issue
