### ISSUE TITLE
`block` and `section` are globally accepted as a defined object in non-section files

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/theme-check#601]
When in a non-section file, such as `templates/cart.liquid`, `section` and `block` are fully accepted as defined.

<img width="673" alt="CleanShot 2022-07-05 at 2 58 26@2x" src="https://user-images.githubusercontent.com/18140157/177345117-c60642b7-fc3d-495f-ade2-620cd2435954.png">

**Comment by lukeh-shopify** [comment]
:wave: Hi @ConduciveMammal, this looks to be updated in the latest version of theme check

<img width="594" alt="image" src="https://github.com/user-attachments/assets/6251f807-1032-44e1-ad7e-06ae7338b70a">

Unfortunately the Ruby version of theme check has been deprecated for some time. Would you be able to confirm you are still having issues when using our [maintained version of theme check](https://shopify.dev/docs/storefronts/themes/tools/theme-check)? This is done using either the latest version of the Shopify CLI, or via the Shopify Liquid Visual Studio Code extension.

If you are still having issues, please raise an issue over in the [CLI](https://github.com/Shopify/cli) or [theme tools](https://github.com/Shopify/theme-tools) repositories. Thanks!
