### ISSUE TITLE
[Bug]: Erroneous MissingTemplate errors when not using default directory structure (supplying [ ROOT ] to theme serve)

### ISSUE THREAD

**Issue by peepers-rick** [Shopify/theme-check#649]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

Using `shopify theme serve [ ROOT ]` where the root is not the default directory structure should NOT result in `theme-check(MissingTemplate)` for all snippets and sections.``

### Actual behavior

Using `shopify theme serve [ ROOT ]` where the root is not the default directory structure shows errors for valid sections and snippets

### Reproduction steps

1. Create theme with non-standard directory structure, example, put assets, config, layout, locales, etc, in a `src` folder
2. Run `shopify theme serve src`
3. Observe that all `{% render %}` `{% include %}` `{% section %}` tags result in a `theme-check(MissingTemplate)`. If you try to click through, it ignores the root (in this case `src`) and looks directly at the default root directory.

### Operating System

Windows 10

### CLI version (run `shopify version` if you're not sure)

2.15.3

### Shell

zsh

### Ruby version (run `ruby -v` if you're not sure)

3.0.1p64

### What language and version are you using in your application?

Liquid

**Comment by bakura10** [comment]
Hi,

I'm trying to migrate from PHPStorm to VS Code, but I am facing the same issue and I can't solve it.

I have created a workspace in VS Code where one folder = one theme.

Each theme has its own .theme-check.yml, and properly reference the `dist` folder in the root option:

<img width="524" alt="image" src="https://github.com/Shopify/theme-check/assets/1198915/12e8b4f8-c799-4506-9227-153ebdc0a35c">

Despite being properly set up, it constantly raise missing templates for all includes (there are, of course, in the folder):

<img width="683" alt="image" src="https://github.com/Shopify/theme-check/assets/1198915/332230f0-199d-4dda-b4d2-59ad43c0b7ff">

How can I make this work?
