### ISSUE TITLE
Validate all the fields in {% schema %}

### ISSUE THREAD

**Issue by macournoyer** [Shopify/theme-check#69]
See https://shopify.dev/docs/themes/sections#using-section-schema-tags for the accepted structure.

However, keep in mind that this page doesn't mention that all values that end up in the UI can be localized. Translation checks in this tag  are part of another issue: #62.

Make sure to check out how a real theme uses this tag for real-world usage.

**Comment by chrisberthe** [comment]
Could be cool to have a setting checker for our JSON which validates required fields (or encourages best practices) on the list of setting types.

Examples: missing `id`, missing `default` key, or `min/max/step` if using `"type": "range"`.

**Comment by lukeh-shopify** [comment]
![image](https://github.com/user-attachments/assets/6211ace6-ff95-4800-a6d7-191f6837ac0f)
