### ISSUE TITLE
Add support for the new item_count_for_variant filter

### ISSUE THREAD

**Issue by bakura10** [Shopify/theme-check#697]
Shopify added silently a new, very useful filter that allows to know how many items has been added for a given variant, independently of the multiple line items (documentation here: https://shopify.dev/api/liquid/filters/item_count_for_variant)

Theme check unfortunately does not support it and raise an error.

**Comment by charlespwd** [comment]
Seems like we do: https://github.com/Shopify/theme-liquid-docs/blob/main/data/filters.json

We have them sync'ed now. Running latest release?

**Comment by karreiro** [comment]
@bakura10 Shopify CLI has been updated with the latest Theme Check version.

I've double-checked and it working fine now:
![demo1](https://user-images.githubusercontent.com/1079279/212898280-e353044d-8bc9-463e-9002-e0f2d13f613e.gif)

Still, please, let us know if I missed something ^
