### ISSUE TITLE
Theme Check requires a new release when new filters are created

### ISSUE THREAD

**Issue by karreiro** [Shopify/theme-check#706]
**Is your feature request related to a problem? Please describe.**

When Theme Check is released, the most updated version of `Shopify/theme-liquid-docs` is embedded. Also, when some new filter is released, local Theme Check instances get auto upgraded asynchronously (so documentation is always updated on developers machines).

However, at CI environments, Theme Check uses the embedded documentation from the latest release, which makes the build of some CI-users fail.

**Describe the solution you'd like**

- Introduce a new flag (something like: `--latest`, `--latest-sources`, `--update-docs`, `--ci`) at Theme Check to synchronously download the latest documentation
- Update `Shopify/theme-check-action` to use that flag

**Describe alternatives you've considered**

- I've considered to just live with this issue and rely on new Theme Check releases

**Comment by charlespwd** [comment]
Do we not have a command to load the updated docs? Can we run it in theme-check-action before linting?

**Comment by karreiro** [comment]
Good catch! We have rake task, but I don't think we currently can execute it from the theme-check-action. Still, running the following script would do the job:

```ruby
require 'theme_check'

ThemeCheck::ShopifyLiquid::SourceManager.download
```

(alternatively, we could expose the `download_theme_liquid_docs` rake task)

**Comment by karreiro** [comment]
Fixed by https://github.com/Shopify/theme-check-action/pull/19.
