### ISSUE TITLE
Theme check 'video_url' type incorrect

### ISSUE THREAD

**Issue by lukecharle** [Shopify/theme-check#726]
**Describe the bug**
Theme check expects a setting of `video_url` to have `accepts` but its actually `accept`

**Expected**
It should not report the error when using `accept`

**Actual**
It shows an error in theme check

<img width="658" alt="Screenshot 2023-04-11 at 16 48 57" src="https://user-images.githubusercontent.com/115987937/231218413-eab05338-e48e-44dd-854c-fcbac6a2da41.png">

<img width="745" alt="Screenshot 2023-04-11 at 16 49 05" src="https://user-images.githubusercontent.com/115987937/231218437-063e7a31-2f70-48ac-a706-db1af43ad3b0.png">

**Additional context**
I'm using the Shopify Liquid VS extension

**Comment by charlespwd** [comment]
You'll note that there isn't a` theme-check($CheckName)` next to the message. This comes from a different plugin.
