### ISSUE TITLE
TranslationKeyExists or MatchingSchemaTranslations or MatchingTranslations with --auto-correct flag replaces contents of every json file with null

### ISSUE THREAD

**Issue by bmandl** [Shopify/theme-check#735]
**Describe the bug**
If theme check for TranslationKeyExists or MatchingSchemaTranslations or MatchingTranslations with --auto-correct flag is run, contents of every json file except default locale json files get replaced with null. 

**Expected**
All json files, except locale json files should stay intact. 

**Actual**
All json files contents gets replaced with null

**Debugging information**
- OS [wsl 2 Ubuntu 20.04]
- Version (1.15.0)

**Comment by lukeh-shopify** [comment]
👋🏻 Hi @bmandl! Thanks for reporting this. Unfortunately the Ruby version of theme check has been deprecated for some time. Would you be able to confirm you are still having issues when using our [maintained version of theme check](https://shopify.dev/docs/storefronts/themes/tools/theme-check)? This is done using either the latest version of the Shopify CLI, or via the Shopify Liquid Visual Studio Code extension.

If you are still having issues, please raise an issue over in the [CLI](https://github.com/Shopify/cli) or [theme tools](https://github.com/Shopify/theme-tools) repositories. Thanks!
