### ISSUE TITLE
TranslationKeyExists issue with section scoped locales

### ISSUE THREAD

**Issue by aurelienbobenrieth** [Shopify/theme-check#736]
**Describe the bug**
It seems there is an issue with ThemeCheck not looking into the section-scoped defined `locales`.

As official doc points out, it is possible to scope `locales` within the section schema see:
https://shopify.dev/docs/themes/architecture/sections/section-schema#locales

**Expected**
I expect the code below (which works just fine) not to generate a theme check error.

```liquid
<span>{{ 'sections.example-section.back-to-top' | t }}</span>

// ...

{% schema %}
{
  "name": "Example section",
  // ...
  "locales": {
    "fr": {
      "back-to-top": "Retour en haut"
    },
    "en": {
      "back-to-top": "Back to top"
    }
  }
}
{% endschema %}
```

**Actual**
```
'sections.example-section.back-to-top' does not have a matching entry in 'locales/en.default.json'
```

**Debugging information**
- OS: Windows 11
- Version: 1.15.0

**Comment by lukeh-shopify** [comment]
👋🏻 Hi @aurelienbobenrieth! Thanks for reporting this. Unfortunately the Ruby version of theme check has been deprecated for some time. Would you be able to confirm you are still having issues when using our [maintained version of theme check](https://shopify.dev/docs/storefronts/themes/tools/theme-check)? This is done using either the latest version of the Shopify CLI, or via the Shopify Liquid Visual Studio Code extension.

If you are still having issues, please raise an issue over in the [CLI](https://github.com/Shopify/cli) or [theme tools](https://github.com/Shopify/theme-tools) repositories. Thanks!
