### ISSUE TITLE
`variable` is never used, is used

### ISSUE THREAD

**Issue by mitchuman** [Shopify/theme-check#737]
**Describe the bug**
Warning: `variable` is never used appears, but the variable is in fact used as in index for an array.

**Expected**
Not give a warning

**Actual**
```
{%- liquid
  for _ in (1..2)
    assign product_num = 'product_' | append: forloop.index
    render 'product-item', product: all_products[block.settings[product_num]]
  endfor
-%}
```
<img width="558" alt="Screen Shot 2023-06-12 at 11 58 03 AM" src="https://github.com/Shopify/theme-check/assets/73133191/452521b5-77c6-416a-8e50-e749255e3748">

**Debugging information**
- mcOS
- VSCode extension v1.10.0

**Additional context**

**Comment by lukeh-shopify** [comment]
👋🏻 Hi @mitchuman! Thanks for reporting this. Unfortunately the Ruby version of theme check has been deprecated for some time. Would you be able to confirm you are still having issues when using our [maintained version of theme check](https://shopify.dev/docs/storefronts/themes/tools/theme-check)? This is done using either the latest version of the Shopify CLI, or via the Shopify Liquid Visual Studio Code extension.

If you are still having issues, please raise an issue over in the [CLI](https://github.com/Shopify/cli) or [theme tools](https://github.com/Shopify/theme-tools) repositories. Thanks!
