### ISSUE TITLE
Fail on theme check

### ISSUE THREAD

**Issue by ivandurst** [Shopify/theme-check#738]
**Stack trace**
```
Theme check failed with error:
┃ /Users/ivandurst/Library/Caches/shopify-gems-nodejs/ruby/3.2.0/gems/theme-check-1.15.0/lib/theme_check/bug.rb:20:in `bug': Can't find a parseable tag of name img inside the parseable HTML. (ThemeCheck::ThemeCheckError)
┃ 
┃ Tag name:
┃   "img"
┃ 
┃ File:
┃   snippets/template-banner.liquid
┃ 
┃ Line number:
┃   10
┃ 
┃ Excerpt:
┃   ```
┃   image: <image object>
┃ mobile_image: <image object>
┃ mobile_crop: <string>
┃ banner_pretext: <string>
┃ banner_text: <string>
┃ banner_subheading: <string>
┃ 
┃   ```
┃ 
┃ Parseable Excerpt:
┃   ```
┃   image: <image object>
┃ mobile_image: <image object>
┃ mobile_crop: <string>
┃ banner_pretext: <string>
┃ banner_text: <string>
┃ banner_subheading: <string>
┃ 
┃   ```
┃ Theme Check Version: 1.15.0
┃ Ruby Version: 3.2.2
┃ Platform: x86_64-darwin21
┃ Muffin mode: activated
```

**Debugging information**
- Mac Monterey
- Version 1.15.0

**Comment by jocelyn-plentiful-commerce** [comment]
+1 for me. I ran 'shopify theme check'.
But I'm on Mac Sonoma 14.0 and version 3

**Comment by chufucious** [comment]
Possibly related? https://github.com/Shopify/theme-check/issues/711

**Comment by lukeh-shopify** [comment]
👋🏻 Hi @chufucious! Thanks for reporting this. Unfortunately the Ruby version of theme check has been deprecated for some time. Would you be able to confirm you are still having issues when using our [maintained version of theme check](https://shopify.dev/docs/storefronts/themes/tools/theme-check)? This is done using either the latest version of the Shopify CLI, or via the Shopify Liquid Visual Studio Code extension.

If you are still having issues, please raise an issue over in the CLI or theme tools repositories. Thanks!
