### ISSUE TITLE
Variables from other files are not recognized

### ISSUE THREAD

**Issue by AldiNFitrah** [Shopify/theme-check#739]
Hi, I'm new to shopify app development. I want to validate a theme but I got so many errors stating that my variables are undefined.

## Bug Description

I declared some variables in file A. Then, in file B, I render file A, and use those variables afterwards. But in theme check, it says that the variables are undefined.

## Expected

Theme check should recognize those variables and does not mark them as offenses.

## Actual

The variables are undefined according to theme check.

## Screenshot
![image](https://github.com/Shopify/theme-check/assets/52171676/0bb5f371-6a73-433d-ade8-a2a616c80687)

## Debugging information
- OS [e.g. Windows, Mac, Linux]: Linux
- Version (output of `theme-check --version` in a terminal): 1.15.0

## Additional context

I am not sure if I installed the tools correctly, but here's what I ran:
```bash
sudo apt install ruby-full
yarn global add @shopify/cli @shopify/theme
gem install bundler
shopify theme check
```

**Comment by lukeh-shopify** [comment]
👋🏻 Hi @AldiNFitrah! Thanks for reporting this. Unfortunately the Ruby version of theme check has been deprecated for some time. Would you be able to confirm you are still having issues when using our [maintained version of theme check](https://shopify.dev/docs/storefronts/themes/tools/theme-check)? This is done using either the latest version of the Shopify CLI, or via the Shopify Liquid Visual Studio Code extension.

If you are still having issues, please raise an issue over in the CLI or theme tools repositories. Thanks!
