### ISSUE TITLE
Typo in editor wiki pages?

### ISSUE THREAD

**Issue by jacobzlogar** [Shopify/theme-check#742]
https://github.com/Shopify/theme-check/wiki/Emacs

> If installed directly (via Homebrew or Ruby Gems), the language server should be on your $PATH as theme-check-liquid-server.

I believe these references should be updated to `theme-check-language-server`

**Comment by jacobzlogar** [comment]
additionally: might be helpful to include a link to the official emacs lsp docs as they include a snippet for configuring a theme-check lsp. https://emacs-lsp.github.io/lsp-mode/page/adding-new-language/
```elisp
;; Use shopify-cli / theme-check-language-server for Shopify's liquid syntax
(with-eval-after-load 'lsp-mode
  (add-to-list 'lsp-language-id-configuration
    '(shopify-mode . "shopify"))

  (lsp-register-client
    (make-lsp-client :new-connection (lsp-stdio-connection "theme-check-language-server")
                     :activation-fn (lsp-activate-on "shopify")
                     :server-id 'theme-check)))

```

**Comment by charlespwd** [comment]
Thanks! Fixed :)
