### ISSUE TITLE
line_items_for filter missing

### ISSUE THREAD

**Issue by bakura10** [Shopify/theme-check#744]
Hi,

The `line_items_for` filter is currently raising an error in the linter: https://shopify.dev/docs/api/liquid/filters/line_items_for
Is it possible to add it ? :)

Thanks.

**Comment by bakura10** [comment]
Any news on this? Unfortunately it seems that each time new filters are released, it takes months for them to be integrated into the platform.

**Comment by charlespwd** [comment]
So we switched to an automatic workflow for this. It seems like the data is there:
https://github.com/Shopify/theme-liquid-docs/blob/main/data/filters.json#L74

And IIRC, there's a job somewhere that pulls the latest docs on check run. In which context do you see the issue? CLI, extension? What version?

**Comment by charlespwd** [comment]
Ah derp the flag is off by default:
https://github.com/Shopify/theme-check/blob/e7bbb91eb35feafc392712cdc7e00d42ef8d558c/lib/theme_check/cli.rb#L210

Try running the CLI with the `--update-docs` flag. That should fix it for you!

**Comment by charlespwd** [comment]
FYI we're in the process of migrating to the TypeScript based implemetation in [Shopify/theme-tools](https://github.com/Shopify/theme-tools). It's fixed over there. 

We're already in dev preview in the VS Code extension (`shopifyLiquid.themeCheckNextDevPreview: true`) and we're coming to the CLI very soon.

**Comment by bakura10** [comment]
I was using the CLI, and adding `--update-docs` flag fixed it! Thanks a lot :)
