### ISSUE TITLE
Getting error "space missing after semicolon". It shouldn't check on comments

### ISSUE THREAD

**Issue by alvinkonda** [Shopify/theme-check#747]
Getting error `space missing after ":"`. It shouldn't check on comments

https://github.com/Shopify/theme-check/blob/main/docs/checks/space_inside_braces.md

<img width="707" alt="Screenshot 2023-10-17 at 10 50 12 AM" src="https://github.com/Shopify/theme-check/assets/273284/e2c0d510-f2f7-4329-84d4-bf1fac3ca2aa">

<img width="573" alt="Screenshot 2023-10-17 at 10 51 49 AM" src="https://github.com/Shopify/theme-check/assets/273284/75f86544-a594-4da9-b75f-27271e654098">

**Comment by charlespwd** [comment]
Yeah that's going away in the next version. (wontfix because already fixed in [Shopify/theme-tools](https://github.com/shopify/theme-tools))
