### ISSUE TITLE
Support for section groups

### ISSUE THREAD

**Issue by nuotsu** [Shopify/theme-check#750]
**Describe the bug**
[Section groups](https://shopify.dev/docs/themes/architecture/section-groups) aren't recognized and the linter displays an error squiggly line.

**Expected**
Not show the linter error line.

**Actual**
The following Liquid code is accurate but shows the squiggly line:

```liquid
{% sections 'header-groups' %}
```

<img width="300" alt="Screenshot 2023-11-26 at 11 24 15 AM" src="https://github.com/Shopify/theme-check/assets/24799299/8c082996-aed9-41a2-9330-2a003eb5a4b8">

**Stack trace**

>Unknown tag 'sections'theme-check ([SyntaxError](https://github.com/Shopify/theme-check/blob/main/docs/checks/syntax_error.md))

**Debugging information**
- MacOS  Sonoma [14.0 (23A344)]
- Version: 1.11.0

**Additional context**

**Comment by charlespwd** [comment]
Yeah all that is going away with theme-check 2.0 coming in this or next week. 🙏 

In the meantime you can try the following in your VS Code settings to start using it right away:
```json
{
  "shopifyLiquid.themeCheckNextDevPreview": true
}
```
