### ISSUE TITLE
Add support for `login_button` filter

### ISSUE THREAD

**Issue by nuotsu** [Shopify/theme-check#751]
**Describe the bug**
[`login_button`](https://shopify.dev/docs/api/liquid/filters/login_button) filter isn't recognized and the linter displays an error squiggly line.

**Expected**
Not show the linter error line.

**Actual**
The following Liquid code is accurate but shows the squiggly line:

```liquid
{{ shop | login_button: action: 'follow' }}
```
<img width="445" alt="Screenshot 2023-11-26 at 11 28 18 AM" src="https://github.com/Shopify/theme-check/assets/24799299/f1740ac9-83bc-435e-873b-81f6f7c6f4e1">

**Stack trace**
> Undefined filter `login_button`theme-check ([UnknownFilter](https://github.com/Shopify/theme-check/blob/main/docs/checks/unknown_filter.md))

**Debugging information**
- MacOS  Sonoma [14.0 (23A344)]
- Version: 1.11.0

**Additional context**

**Comment by charlespwd** [comment]
Same as https://github.com/Shopify/theme-check/issues/750

Try the following in your vscode settings.json

```
{
  "shopifyLiquid.themeCheckNextDevPreview": true
}
```
