### ISSUE TITLE
Allow filters to include `avatar` 

### ISSUE THREAD

**Issue by sofiamatulis** [Shopify/theme-check#759]
This PR shipped an `avatar filter` and we are getting some `theme check` errors:

Error: https://screenshot.click/09-36-57cxl-8l1v5.png
PR: https://github.com/Shopify/dawn/pull/3376

cc @mtbottens

**Comment by charlespwd** [comment]
It's an internal documentation issue, docs are automatically pulled into Shopify/theme-liquid-docs and into shopify.dev. The docs must be added where the filter was added.
